### ISSUE TITLE
TypeError: HowlConstructor.current is not a constructor

### ISSUE THREAD

**Issue by PuruVJ** [joshwcomeau/use-sound#60]
I am having the error mentioned above while using use-sound with Vite and React.

- Howler JS is being loaded, in the networks panel in devtools
- Error is here:
![image](https://user-images.githubusercontent.com/47742487/108634531-ed9c5600-749f-11eb-9d9c-04dd505d2398.png)

Pls help.
Thank you

**Comment by apilacharya** [comment]
Same error here.

**Comment by PuruVJ** [comment]
> Same error here. If you've find the fix please mention.

Not yet. I've moved on to using plain `<audio >` tag and programmatically triggering, as that was enough for my use case

**Comment by joshwcomeau** [comment]
If anyone does find a fix, feel free to submit a PR! I'm not familiar with Vite so I can't offer any help

**Comment by DrSensor** [comment]
I think this issue should be kept open for visibility (making it easier to search)

**Comment by joshwcomeau** [comment]
I believe this should be fixed now, thanks to @DrSensor's PR.

**Comment by devonpmack** [comment]
Hi, the issue is still occurring, I believe because the fix hasn't actually been shipped to NPM. @joshwcomeau could you please cut a release with @DrSensor's fix? Thank you!
